### ISSUE TITLE
Autotithing sending illegal tithes

### ISSUE THREAD

**Issue by vahtis** [biblepay/biblepay#82]
See transaction
885cbeac1d34e1544fd1d427da077e6fcd2aef42ce37405186a32ed5f59071f2

This relates to #78

**Comment by vahtis** [comment]
exec istithelegal  885cbeac1d34e1544fd1d427da077e6fcd2aef42ce37405186a32ed5f59071f2

{
  "Command": "istithelegal",
  "Tithe_Legal": -3,
  "Tithe_Legal_Result": "TITHE_TOO_HIGH",
  "Tx_Time": 1550985473,
  "Tithed_Height": 103418,
  "Spent_Time": 1550593294,
  "Spent_Height": 102509,
  "Spent_Coin_Amount": 1727.3008362,
  "Tithe_Age": 4.539108796296296,
  "Tithe_Amount": 9.43,
  "Block_diff_min_coin_age": 6.28,
  "Block_diff_min_coin_amt": 2525,
  "Block_diff_max_tithe_amt": 9
}

**Comment by vahtis** [comment]
This happened to me during testing. When I extracted max tithe from titheinfo to nnn and used exec tithe nnn
Sorry I forgot to mention at that time.

**Comment by biblepay** [comment]
Ok, your right, so I audited 50 transactions that appear to be auto tithed (based on the bbp sent compared to the diff level) and it appears our auto tithe system is rounding Up to the next penny while our diff level is being trucated at 2 digits.  Since I dont want to go too far, and change the UI tithe or the RPC tithe, Im just changing the miner right now.  To send .01 bbp less in auto mode.

Please let me know if you think this fixes the issue 100%.  (It does from the looks of the data).

**Comment by sunk818** [comment]
Fixed in [1.1.9.4](https://github.com/biblepay/biblepay/commit/3be1ffeb981025498ff56fc835e2d67e74dd1154) and value display consistency in [1.1.9.4b](https://github.com/biblepay/biblepay/commit/263276494e03dc7ef3add2f16d1f2f6c444c9140)

**Comment by sunk818** [comment]
> capulo had same issue.

hmm i have some issue:
i had 17 transactions between 2 tithe payouts:

![image](https://user-images.githubusercontent.com/6989799/53315345-7ebba080-3877-11e9-9f6d-955c99565ddc.png)

and if i check piles in coin control i can see they were touched:

![image](https://user-images.githubusercontent.com/6989799/53315352-8c712600-3877-11e9-9b32-4d4935f14e48.png)

BUT, if i check pogpool then i see, that i only did 24 bbp as tithe in last 205 blocks:

![image](https://user-images.githubusercontent.com/6989799/53315369-a01c8c80-3877-11e9-878c-2b950f28b405.png)

also payout was adequate for tithes ~24bbp

ps: i had few tx (about 5) not sent, they were offline, i needed to restart wallet and then they gets counted

ps2: if i did 3x 8.1 bbp tithe, why it is in pogpool report as 24.00 and not 24.30? Smiley or from other view, if there are only whole numbers counted as tithe, why autotithe is sending also decimals?

**Rob said:**

> Looks like problem #1 is auto-tithe should have sent 8.09 not 8.101 from your client (fixed in 1.1.9.4)
> Looks like problem #2 is PogPool and PogPool UI aren't displaying the full scale, fixed in 1.1.9.4.
> 
> Preparing a new release.

**Comment by sunk818** [comment]
Fixed in [1.1.9.4](https://github.com/biblepay/biblepay/commit/3be1ffeb981025498ff56fc835e2d67e74dd1154) and value display consistency in [1.1.9.4b](https://github.com/biblepay/biblepay/commit/263276494e03dc7ef3add2f16d1f2f6c444c9140)

**Comment by biblepay** [comment]
Ok, good, glad it worked.  We can tackle the orphaned transactions as a separate issue if 1195 does not fix them.  In 1195, we pre-check to see if tithing will result in a rejected tithe (preventing the orphan).
